version: '3.8'
services:
  db:
    container_name: expense-manager-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bgtbhuBGTBHU
      POSTGRES_DB: expense-management-service
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

